openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/noticias:
    get:
      summary: Noticias
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Noticias
      security: []
    post:
      summary: Salvar
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Noticias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conteudo:
                  type: string
                  description: 'optional Conteúdo.'
                  example: 'The government has'
                subtitulo:
                  type: string
                  description: 'optional Sub-título.'
                  example: 'Abbott government'
                fonte:
                  type: string
                  description: 'optional Fonte.'
                  example: 'The Guardian'
                titulo:
                  type: string
                  description: Fonte.
                  example: 'Heatwave frequency'
                data_publicacao:
                  type: string
                  description: 'optional Data Publicação.'
                  example: '2014-02-17T14:04:00'
                url:
                  type: string
                  description: 'optional URL.'
                  example: 'http://www.theguardian.com'
              required:
                - titulo
      security: []
  '/api/noticias/{id}':
    get:
      summary: 'Noticias (id)'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Notícia não encontrada'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Notícia não encontrada'
      tags:
        - Noticias
      security: []
    put:
      summary: Atualizar
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Noticias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conteudo:
                  type: string
                  description: 'optional Conteúdo.'
                  example: 'The government has'
                subtitulo:
                  type: string
                  description: 'optional Sub-título.'
                  example: 'Abbott government'
                fonte:
                  type: string
                  description: 'optional Fonte.'
                  example: 'The Guardian'
                titulo:
                  type: string
                  description: Fonte.
                  example: 'Heatwave frequency'
                data_publicacao:
                  type: string
                  description: 'optional Data Publicação.'
                  example: '2014-02-17T14:04:00'
                url:
                  type: string
                  description: 'optional URL.'
                  example: 'http://www.theguardian.com'
              required:
                - titulo
      security: []
    delete:
      summary: Deletar
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Noticias
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'ID da Noticia.'
        example: '1'
        required: true
        schema:
          type: string
  /api/noticias/lote:
    post:
      summary: 'Salvar em Lote'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Noticias
      security: []
  /api/noticias/elastic:
    get:
      summary: 'Noticias Elastic'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error:
                    root_cause:
                      -
                        type: index_not_found_exception
                        reason: 'no such index [noticias]'
                        resource.type: index_or_alias
                        resource.id: noticias
                        index_uuid: _na_
                        index: noticias
                    type: index_not_found_exception
                    reason: 'no such index [noticias]'
                    resource.type: index_or_alias
                    resource.id: noticias
                    index_uuid: _na_
                    index: noticias
                  status: 404
                properties:
                  error:
                    type: object
                    example:
                      root_cause:
                        -
                          type: index_not_found_exception
                          reason: 'no such index [noticias]'
                          resource.type: index_or_alias
                          resource.id: noticias
                          index_uuid: _na_
                          index: noticias
                      type: index_not_found_exception
                      reason: 'no such index [noticias]'
                      resource.type: index_or_alias
                      resource.id: noticias
                      index_uuid: _na_
                      index: noticias
                  status:
                    type: integer
                    example: 404
      tags:
        - Noticias
      security: []
  '/api/noticias/elastic/{id}':
    get:
      summary: 'Noticias Elastic (id)'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error:
                    root_cause:
                      -
                        type: index_not_found_exception
                        reason: 'no such index [noticias]'
                        resource.type: index_expression
                        resource.id: noticias
                        index_uuid: _na_
                        index: noticias
                    type: index_not_found_exception
                    reason: 'no such index [noticias]'
                    resource.type: index_expression
                    resource.id: noticias
                    index_uuid: _na_
                    index: noticias
                  status: 404
                properties:
                  error:
                    type: object
                    example:
                      root_cause:
                        -
                          type: index_not_found_exception
                          reason: 'no such index [noticias]'
                          resource.type: index_expression
                          resource.id: noticias
                          index_uuid: _na_
                          index: noticias
                      type: index_not_found_exception
                      reason: 'no such index [noticias]'
                      resource.type: index_expression
                      resource.id: noticias
                      index_uuid: _na_
                      index: noticias
                  status:
                    type: integer
                    example: 404
      tags:
        - Noticias
      security: []
    delete:
      summary: 'Noticias Elastic All'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Noticias
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'ID da Noticia.'
        example: '1'
        required: true
        schema:
          type: string
